name: Fetch data

# Controls when the workflow will run
on:
  schedule:
    # Runs "at hour x past every day" (see https://crontab.guru)
    - cron: '00 14 * * *'
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Download playlist.m3u file
        id: download_playlist
        run: |
          http_code=$(curl -s -L \
            -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" \
            -w "%{http_code}" \
            -o playlist.m3u \
            "http://m3u4u.com/m3u/p87vnr5wegu44qe8y41j")
            
          if [[ "$http_code" != "200" && "$http_code" != "302" ]]; then
            echo "Download failed with HTTP code $http_code"
            exit 1
          fi

          sleep 2
          
          file_size=$(stat -c%s "playlist.m3u")
          if [[ "$file_size" -le 0 ]]; then
            echo "File size is too small: $file_size bytes"
            exit 1
          fi
        
      - name: Download EPG-Guide.xml.gz file
        id: download_epg
        run: |
          http_code=$(curl -s -L \
            -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" \
            -w "%{http_code}" \
            -o EPG-Guide.xml.gz \
            "http://combate.asia/xmltv.php?username=077551817515&password=6268049625318")
            
          if [[ "$http_code" != "200" && "$http_code" != "302" ]]; then
            echo "Download failed with HTTP code $http_code"
            exit 1
          fi

          sleep 2
          
          file_size=$(stat -c%s "EPG-Guide.xml.gz")
          if [[ "$file_size" -le 0 ]]; then
            echo "File size is too small: $file_size bytes"
            exit 1
          fi
      
      - name: Commit changes if updated
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add playlist.m3u
          git add EPG-Guide.xml.gz
          git diff-index --quiet HEAD || git commit -m "actions-user: Fetch data workflow" -a
          git push -f origin main:main
        if: success()
